title: Assume For Simplicity
email: webmaster@assumeforsimplicity.com
description: >- # this means to ignore newlines until "baseurl:"
  Manage Time, Software, and Business, Easily  
baseurl: "/roguelike-tutorial/" # the subpath of your site, e.g. /blog
url: "https://assumeforsimplicity.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jr101dallas
auhor:  jr101dallas
future: false

# Build settings
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag